<?php
session_start();
if (!isset($_SESSION['user'])) {
    header("Location: /api/login.php");
    exit();
}

include 'config.php';

// Check if portal is configured
if (empty($host)) {
    header('Content-Type: text/plain');
    die("#EXTM3U\n# Error: Portal not configured. Please set up your portal first.");
}

$Bearer_token = (file_exists($tokenFile) && filesize($tokenFile)) ? file_get_contents($tokenFile) : generate_token();

// Check if we have cached playlist
$playlist_file = $directories["playlist"] . "/{$host}.m3u";
$use_cache = !isset($_GET['refresh']);

if ($use_cache && file_exists($playlist_file) && (time() - filemtime($playlist_file)) < 3600) {
    // Serve cached playlist if it's less than 1 hour old
    header('Content-Type: audio/x-mpegurl');
    header('Content-Disposition: attachment; filename="playlist.m3u"');
    readfile($playlist_file);
    exit;
}

function getChannels($host, $Bearer_token, $mac) {
    $url = "http://$host/stalker_portal/server/load.php?type=itv&action=get_all_channels&JsHttpRequest=1-xml";
    
    $headers = [
        "Cookie: timezone=GMT; stb_lang=en; mac=$mac",
        "Referer: http://$host/stalker_portal/c/",
        "Accept: */*",
        "User-Agent: Mozilla/5.0 (QtEmbedded; U; Linux; C) AppleWebKit/533.3 (KHTML, like Gecko) MAG200 stbapp ver: 2 rev: 250 Safari/533.3",
        "X-User-Agent: Model: MAG250; Link: WiFi",
        "Authorization: Bearer $Bearer_token",
        "Host: $host",
        "Connection: Keep-Alive",
        "Accept-Encoding: gzip"
    ];
    
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => 'gzip',
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_SSL_VERIFYPEER => false,
    ]);
    
    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    
    if ($httpCode !== 200 || empty($response)) {
        throw new Exception("Failed to fetch channels from portal. HTTP Code: $httpCode");
    }
    
    $data = json_decode($response, true);
    if (json_last_error() !== JSON_ERROR_NONE || !isset($data['js']['data'])) {
        throw new Exception("Invalid response from portal");
    }
    
    return $data['js']['data'];
}

function getFilteredGroups() {
    global $directories, $host;
    $filter_file = $directories["filter"] . "/$host.json";
    
    if (!file_exists($filter_file)) {
        return [];
    }
    
    $filters = json_decode(file_get_contents($filter_file), true);
    if ($filters === null) {
        return [];
    }
    
    $filtered_groups = [];
    foreach ($filters as $id => $filter) {
        if (isset($filter['filter']) && $filter['filter'] === true) {
            $filtered_groups[$id] = $filter['title'];
        }
    }
    
    return $filtered_groups;
}

function generatePlaylist($channels, $base_url) {
    $filtered_groups = getFilteredGroups();
    $playlist = "#EXTM3U\n";
    $playlist .= "# Playlist generated by mac2m3u\n";
    $playlist .= "# Generated: " . date('Y-m-d H:i:s') . "\n";
    $playlist .= "# Base URL: " . $base_url . "\n\n";
    
    $channel_count = 0;
    
    foreach ($channels as $channel) {
        if (!isset($channel['id'], $channel['name'], $channel['number'])) {
            continue;
        }
        
        // Apply group filtering
        if (!empty($filtered_groups)) {
            $channel_genres = isset($channel['tv_genre_id']) ? (array)$channel['tv_genre_id'] : [];
            $has_matching_genre = false;
            
            foreach ($channel_genres as $genre_id) {
                if (isset($filtered_groups[$genre_id])) {
                    $has_matching_genre = true;
                    break;
                }
            }
            
            if (!$has_matching_genre) {
                continue;
            }
        }
        
        $channel_id = $channel['id'];
        $channel_name = htmlspecialchars($channel['name']);
        $channel_number = $channel['number'];
        $logo = isset($channel['logo']) ? htmlspecialchars($channel['logo']) : '';
        
        // Get group name
        $group_title = 'General';
        if (isset($channel['tv_genre_id'])) {
            $genre_ids = (array)$channel['tv_genre_id'];
            foreach ($genre_ids as $genre_id) {
                if (isset($filtered_groups[$genre_id])) {
                    $group_title = $filtered_groups[$genre_id];
                    break;
                }
            }
        }
        
        // Create stream URL - using the Vercel function URL
        $stream_url = $base_url . "play.php?id=" . $channel_id;
        
        // Add channel to playlist
        $playlist .= "#EXTINF:-1 tvg-id=\"$channel_id\" tvg-name=\"$channel_name\" tvg-logo=\"$logo\" group-title=\"$group_title\",$channel_name\n";
        $playlist .= "$stream_url\n\n";
        
        $channel_count++;
    }
    
    $playlist .= "# End of playlist\n";
    $playlist .= "# Filtered channels: $channel_count\n";
    
    return $playlist;
}

try {
    // Get channels from portal
    $channels = getChannels($host, $Bearer_token, $mac);
    
    if (empty($channels)) {
        throw new Exception("No channels found in portal response");
    }
    
    // Generate base URL for stream links
    $base_url = "https://" . $_SERVER['HTTP_HOST'] . "/api/";
    
    // Generate playlist
    $playlist_content = generatePlaylist($channels, $base_url);
    
    // Cache the playlist
    file_put_contents($playlist_file, $playlist_content);
    
    // Output playlist
    header('Content-Type: audio/x-mpegurl');
    header('Content-Disposition: attachment; filename="playlist_' . $host . '.m3u"');
    header('Content-Length: ' . strlen($playlist_content));
    echo $playlist_content;
    
} catch (Exception $e) {
    header('Content-Type: text/plain');
    $error_message = "#EXTM3U\n# Error: " . $e->getMessage() . "\n";
    $error_message .= "# Please check your portal configuration and try again.\n";
    echo $error_message;
}
?>
