<?php
// Check if user is logged in
if (!isset($_SESSION['user'])) {
    header("HTTP/1.1 401 Unauthorized");
    echo "Unauthorized";
    exit();
}

// Simple playlist response for now
header('Content-Type: audio/x-mpegurl');
header('Content-Disposition: attachment; filename="playlist.m3u"');

echo "#EXTM3U\n";
echo "# Playlist generated by mac2m3u\n";
echo "# This is a demo playlist\n";
echo "# Configure your portal to get real channels\n\n";
echo "#EXTINF:-1, Demo Channel 1\n";
echo "http://example.com/stream1\n\n";
echo "#EXTINF:-1, Demo Channel 2\n";
echo "http://example.com/stream2\n";
?>
